
build:
	gcc geradorConexoMundoPequeno.c -o geradorConexoMundoPequeno -Wall -Wextra -Werror
	gcc geradorDesconexo.c -o geradorDesconexo -Wall -Wextra -Werror
clean:
	rm geradorConexoMundoPequeno
	rm geradorDesconexo

